[package]
name = "semanticworks-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
log = "0.4.29"
indicatif = "0.18.3"
ansi_term = "0.12.1"